[package]
name = "kaduda"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.10", features = ["derive"] }
include_dir = "0.7.3"
memmap2 = "0.5.10"
object = "0.30.3"
